services:
  api:
    image: tilersmyth/tauri-test-api:latest
    container_name: tauri-api
    ports: 
      - 3000:3000
    depends_on:
      db:
        condition: service_started
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  db:
    image: postgres:16-alpine
    container_name: tauri-db
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB